services:
  proxy:
    ports:
      - "8030:80"
      - "8093:8080"
  db:
    ports:
      - "5435:5432"
  backend:
    volumes:
      - ./backend/app:/app/app
      - ./backend/tests:/app/tests
      - agent-artifacts:/data/agent_artifacts
    environment:
      - POSTGRES_PORT=5432
  orchestrator:
    volumes:
      - ./backend/app:/app/app
      - ./backend/tests:/app/tests
      - agent-artifacts:/data/agent_artifacts
    environment:
      - POSTGRES_PORT=5432
  celery_worker:
    environment:
      - POSTGRES_PORT=5432
  prestart:
    environment:
      - POSTGRES_PORT=5432
