// This file is auto-generated by @hey-api/openapi-ts

export const AgentArtifactPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id',
            description: 'Unique artifact identifier'
        },
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id',
            description: 'ID of the session this artifact belongs to'
        },
        artifact_type: {
            type: 'string',
            title: 'Artifact Type',
            description: 'Type of artifact (model, plot, report, code, data)'
        },
        name: {
            type: 'string',
            title: 'Name',
            description: 'Name of the artifact'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description',
            description: 'Description of the artifact'
        },
        file_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Path',
            description: 'Storage path'
        },
        mime_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mime Type',
            description: 'MIME type'
        },
        size_bytes: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size Bytes',
            description: 'Size in bytes'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At',
            description: 'Artifact creation timestamp'
        },
        is_loading: {
            type: 'boolean',
            title: 'Is Loading',
            description: 'Indicates if the data is currently being refreshed or computed.',
            default: false
        },
        last_updated: {
            type: 'string',
            format: 'date-time',
            title: 'Last Updated',
            description: 'Timestamp when the data was last updated.'
        },
        data_staleness_seconds: {
            type: 'number',
            title: 'Data Staleness Seconds',
            description: 'Number of seconds since the data was last updated.',
            default: 0
        }
    },
    type: 'object',
    required: ['id', 'session_id', 'artifact_type', 'name', 'created_at'],
    title: 'AgentArtifactPublic',
    description: 'Schema for returning agent artifact via API'
} as const;

export const AgentSessionCreateSchema = {
    properties: {
        user_goal: {
            type: 'string',
            maxLength: 5000,
            minLength: 1,
            title: 'User Goal',
            description: 'Natural language trading goal'
        }
    },
    type: 'object',
    required: ['user_goal'],
    title: 'AgentSessionCreate',
    description: 'Schema for creating a new agent session'
} as const;

export const AgentSessionMessagePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id',
            description: 'Unique message identifier'
        },
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id',
            description: 'ID of the session this message belongs to'
        },
        role: {
            type: 'string',
            title: 'Role',
            description: 'Role of the sender (user, assistant, system, function)'
        },
        content: {
            type: 'string',
            title: 'Content',
            description: 'Content of the message'
        },
        agent_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Agent Name',
            description: 'Name of the specific agent'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At',
            description: 'Message creation timestamp'
        },
        is_loading: {
            type: 'boolean',
            title: 'Is Loading',
            description: 'Indicates if the data is currently being refreshed or computed.',
            default: false
        },
        last_updated: {
            type: 'string',
            format: 'date-time',
            title: 'Last Updated',
            description: 'Timestamp when the data was last updated.'
        },
        data_staleness_seconds: {
            type: 'number',
            title: 'Data Staleness Seconds',
            description: 'Number of seconds since the data was last updated.',
            default: 0
        }
    },
    type: 'object',
    required: ['id', 'session_id', 'role', 'content', 'created_at'],
    title: 'AgentSessionMessagePublic',
    description: 'Schema for returning agent session message via API'
} as const;

export const AgentSessionPublicSchema = {
    properties: {
        user_goal: {
            type: 'string',
            title: 'User Goal',
            description: 'Natural language trading goal from user'
        },
        status: {
            type: 'string',
            title: 'Status',
            description: 'Current status (pending, running, completed, failed, cancelled)'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id',
            description: 'Unique session identifier'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id',
            description: 'ID of the user who owns this session'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message',
            description: 'Error message if failed'
        },
        result_summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Result Summary',
            description: 'Summary of the session results'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At',
            description: 'Session creation timestamp'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At',
            description: 'Last update timestamp'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At',
            description: 'Completion timestamp'
        },
        is_loading: {
            type: 'boolean',
            title: 'Is Loading',
            description: 'Indicates if the data is currently being refreshed or computed.',
            default: false
        },
        last_updated: {
            type: 'string',
            format: 'date-time',
            title: 'Last Updated',
            description: 'Timestamp when the data was last updated.'
        },
        data_staleness_seconds: {
            type: 'number',
            title: 'Data Staleness Seconds',
            description: 'Number of seconds since the data was last updated.',
            default: 0
        }
    },
    type: 'object',
    required: ['user_goal', 'status', 'id', 'user_id', 'created_at', 'updated_at'],
    title: 'AgentSessionPublic',
    description: 'Schema for returning agent session via API'
} as const;

export const AgentSessionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AgentSessionPublic'
            },
            type: 'array',
            title: 'Data',
            description: 'List of agent sessions'
        },
        count: {
            type: 'integer',
            title: 'Count',
            description: 'Total count of sessions'
        },
        is_loading: {
            type: 'boolean',
            title: 'Is Loading',
            description: 'Indicates if the data is currently being refreshed or computed.',
            default: false
        },
        last_updated: {
            type: 'string',
            format: 'date-time',
            title: 'Last Updated',
            description: 'Timestamp when the data was last updated.'
        },
        data_staleness_seconds: {
            type: 'number',
            title: 'Data Staleness Seconds',
            description: 'Number of seconds since the data was last updated.',
            default: 0
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AgentSessionsPublic',
    description: 'Schema for returning multiple agent sessions'
} as const;

export const ApprovalDecisionSchema = {
    properties: {
        approved: {
            type: 'boolean',
            title: 'Approved'
        },
        reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        }
    },
    type: 'object',
    required: ['approved'],
    title: 'ApprovalDecision',
    description: 'User approval or rejection.'
} as const;

export const AuditLogPublicSchema = {
    properties: {
        event_type: {
            type: 'string',
            maxLength: 100,
            title: 'Event Type'
        },
        severity: {
            type: 'string',
            maxLength: 20,
            title: 'Severity',
            default: 'info'
        },
        details: {
            additionalProperties: true,
            type: 'object',
            title: 'Details',
            default: {}
        },
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Timestamp'
        }
    },
    type: 'object',
    required: ['event_type', 'id', 'timestamp'],
    title: 'AuditLogPublic'
} as const;

export const AuditLogsSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AuditLogPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AuditLogs'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ChoiceSelectionSchema = {
    properties: {
        selected_model: {
            type: 'string',
            title: 'Selected Model'
        }
    },
    type: 'object',
    required: ['selected_model'],
    title: 'ChoiceSelection',
    description: 'User selection from available choices.'
} as const;

export const ClarificationResponseSchema = {
    properties: {
        responses: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Responses'
        }
    },
    type: 'object',
    required: ['responses'],
    title: 'ClarificationResponse',
    description: 'User responses to clarification questions.'
} as const;

export const CoinspotCredentialsCreateSchema = {
    properties: {
        api_key: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Api Key'
        },
        api_secret: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Api Secret'
        }
    },
    type: 'object',
    required: ['api_key', 'api_secret'],
    title: 'CoinspotCredentialsCreate',
    description: 'Schema for creating Coinspot credentials'
} as const;

export const CoinspotCredentialsPublicSchema = {
    properties: {
        is_validated: {
            type: 'boolean',
            title: 'Is Validated'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        api_key_masked: {
            type: 'string',
            title: 'Api Key Masked',
            description: 'Masked API key (last 4 characters visible)'
        },
        last_validated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Validated At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['is_validated', 'id', 'user_id', 'api_key_masked', 'last_validated_at', 'created_at', 'updated_at'],
    title: 'CoinspotCredentialsPublic',
    description: 'Schema for returning Coinspot credentials via API (with masked values)'
} as const;

export const CoinspotCredentialsUpdateSchema = {
    properties: {
        api_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Key'
        },
        api_secret: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Secret'
        }
    },
    type: 'object',
    title: 'CoinspotCredentialsUpdate',
    description: 'Schema for updating Coinspot credentials'
} as const;

export const CollectorCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        type: {
            type: 'string',
            maxLength: 50,
            title: 'Type'
        },
        config: {
            additionalProperties: true,
            type: 'object',
            title: 'Config'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        schedule: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Schedule'
        }
    },
    type: 'object',
    required: ['name', 'type'],
    title: 'CollectorCreate'
} as const;

export const CollectorPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        type: {
            type: 'string',
            maxLength: 50,
            title: 'Type'
        },
        config: {
            additionalProperties: true,
            type: 'object',
            title: 'Config'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        schedule: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Schedule'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        last_run_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Run At'
        },
        last_status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Status'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'type', 'id', 'last_run_at', 'last_status', 'created_at', 'updated_at'],
    title: 'CollectorPublic'
} as const;

export const CollectorUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Type'
        },
        config: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Config'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        schedule: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Schedule'
        }
    },
    type: 'object',
    title: 'CollectorUpdate'
} as const;

export const CollectorsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CollectorPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CollectorsPublic'
} as const;

export const ControlResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['status', 'message'],
    title: 'ControlResponse'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HistoricalPnLEntrySchema = {
    properties: {
        is_loading: {
            type: 'boolean',
            title: 'Is Loading',
            description: 'Indicates if the data is currently being refreshed or computed.',
            default: false
        },
        last_updated: {
            type: 'string',
            format: 'date-time',
            title: 'Last Updated',
            description: 'Timestamp when the data was last updated.'
        },
        data_staleness_seconds: {
            type: 'number',
            title: 'Data Staleness Seconds',
            description: 'Number of seconds since the data was last updated.',
            default: 0
        },
        timestamp: {
            type: 'string',
            title: 'Timestamp',
            description: 'ISO 8601 timestamp of the entry'
        },
        realized_pnl: {
            type: 'number',
            title: 'Realized Pnl',
            description: 'Realized P&L value for this interval'
        },
        interval: {
            type: 'string',
            title: 'Interval',
            description: 'Time interval (hour, day, week, month)'
        }
    },
    type: 'object',
    required: ['timestamp', 'realized_pnl', 'interval'],
    title: 'HistoricalPnLEntry',
    description: 'Single entry in historical P&L data'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const OrderPublicSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id',
            description: 'The UUID of the user placing the order.'
        },
        algorithm_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Algorithm Id',
            description: 'The UUID of the algorithm that placed this order, if any.'
        },
        coin_type: {
            type: 'string',
            maxLength: 20,
            title: 'Coin Type',
            description: "The type of coin (e.g., 'BTC', 'ETH')."
        },
        side: {
            type: 'string',
            maxLength: 10,
            title: 'Side',
            description: "The side of the order ('buy' or 'sell')."
        },
        order_type: {
            type: 'string',
            maxLength: 20,
            title: 'Order Type',
            description: "The type of order ('market' or 'limit').",
            default: 'market'
        },
        quantity: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Quantity',
            description: 'The quantity to buy or sell.'
        },
        price: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price',
            description: 'The price for limit orders. Optional for market orders.'
        },
        filled_quantity: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Filled Quantity',
            description: 'The quantity that has been filled so far.',
            default: '0'
        },
        status: {
            type: 'string',
            maxLength: 20,
            title: 'Status',
            description: "The status of the order (e.g., 'pending', 'filled', 'cancelled').",
            default: 'pending'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message',
            description: 'Error message if the order failed.'
        },
        coinspot_order_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Coinspot Order Id',
            description: 'The ID of the order on CoinSpot.'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id',
            description: 'The unique identifier for the order.'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At',
            description: 'The timestamp when the order was created.'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At',
            description: 'The timestamp when the order was last updated.'
        },
        submitted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Submitted At',
            description: 'The timestamp when the order was submitted.'
        },
        filled_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Filled At',
            description: 'The timestamp when the order was filled.'
        }
    },
    type: 'object',
    required: ['user_id', 'coin_type', 'side', 'quantity', 'id', 'created_at', 'updated_at', 'submitted_at', 'filled_at'],
    title: 'OrderPublic',
    description: 'Schema for returning order via API'
} as const;

export const OrderRequestSchema = {
    properties: {
        coin_type: {
            type: 'string',
            maxLength: 20,
            title: 'Coin Type',
            description: "The type of coin (e.g., 'BTC', 'ETH')."
        },
        side: {
            type: 'string',
            maxLength: 10,
            title: 'Side',
            description: "The side of the order ('buy' or 'sell')."
        },
        order_type: {
            type: 'string',
            maxLength: 20,
            title: 'Order Type',
            description: "The type of order ('market' or 'limit').",
            default: 'market'
        },
        quantity: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Quantity',
            description: 'The quantity to buy or sell.'
        },
        price: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price',
            description: 'The price for limit orders. Optional for market orders.'
        },
        algorithm_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Algorithm Id',
            description: 'The UUID of the algorithm placing the order.'
        }
    },
    type: 'object',
    required: ['coin_type', 'side', 'quantity'],
    title: 'OrderRequest',
    description: 'Request schema for placing a new order'
} as const;

export const OrderResponseSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id',
            description: 'The UUID of the user placing the order.'
        },
        algorithm_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Algorithm Id',
            description: 'The UUID of the algorithm that placed this order, if any.'
        },
        coin_type: {
            type: 'string',
            maxLength: 20,
            title: 'Coin Type',
            description: "The type of coin (e.g., 'BTC', 'ETH')."
        },
        side: {
            type: 'string',
            maxLength: 10,
            title: 'Side',
            description: "The side of the order ('buy' or 'sell')."
        },
        order_type: {
            type: 'string',
            maxLength: 20,
            title: 'Order Type',
            description: "The type of order ('market' or 'limit').",
            default: 'market'
        },
        quantity: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Quantity',
            description: 'The quantity to buy or sell.'
        },
        price: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price',
            description: 'The price for limit orders. Optional for market orders.'
        },
        filled_quantity: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Filled Quantity',
            description: 'The quantity that has been filled so far.',
            default: '0'
        },
        status: {
            type: 'string',
            maxLength: 20,
            title: 'Status',
            description: "The status of the order (e.g., 'pending', 'filled', 'cancelled').",
            default: 'pending'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message',
            description: 'Error message if the order failed.'
        },
        coinspot_order_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Coinspot Order Id',
            description: 'The ID of the order on CoinSpot.'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id',
            description: 'The unique identifier for the order.'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At',
            description: 'The timestamp when the order was created.'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At',
            description: 'The timestamp when the order was last updated.'
        },
        submitted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Submitted At',
            description: 'The timestamp when the order was submitted.'
        },
        filled_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Filled At',
            description: 'The timestamp when the order was filled.'
        }
    },
    type: 'object',
    required: ['user_id', 'coin_type', 'side', 'quantity', 'id', 'created_at', 'updated_at', 'submitted_at', 'filled_at'],
    title: 'OrderResponse',
    description: 'Response schema for an order'
} as const;

export const OverrideRequestSchema = {
    properties: {
        override_type: {
            type: 'string',
            title: 'Override Type'
        },
        override_data: {
            additionalProperties: true,
            type: 'object',
            title: 'Override Data'
        }
    },
    type: 'object',
    required: ['override_type', 'override_data'],
    title: 'OverrideRequest',
    description: 'User override request.'
} as const;

export const PnLByAlgorithmResponseSchema = {
    properties: {
        is_loading: {
            type: 'boolean',
            title: 'Is Loading',
            description: 'Indicates if the data is currently being refreshed or computed.',
            default: false
        },
        last_updated: {
            type: 'string',
            format: 'date-time',
            title: 'Last Updated',
            description: 'Timestamp when the data was last updated.'
        },
        data_staleness_seconds: {
            type: 'number',
            title: 'Data Staleness Seconds',
            description: 'Number of seconds since the data was last updated.',
            default: 0
        },
        algorithm_id: {
            type: 'string',
            title: 'Algorithm Id',
            description: 'Unique identifier of the trading algorithm'
        },
        realized_pnl: {
            type: 'number',
            title: 'Realized Pnl',
            description: 'Realized P&L for this algorithm'
        },
        unrealized_pnl: {
            type: 'number',
            title: 'Unrealized Pnl',
            description: 'Unrealized P&L for this algorithm'
        },
        total_pnl: {
            type: 'number',
            title: 'Total Pnl',
            description: 'Total P&L for this algorithm'
        }
    },
    type: 'object',
    required: ['algorithm_id', 'realized_pnl', 'unrealized_pnl', 'total_pnl'],
    title: 'PnLByAlgorithmResponse',
    description: 'Response model for P&L grouped by algorithm'
} as const;

export const PnLByCoinResponseSchema = {
    properties: {
        is_loading: {
            type: 'boolean',
            title: 'Is Loading',
            description: 'Indicates if the data is currently being refreshed or computed.',
            default: false
        },
        last_updated: {
            type: 'string',
            format: 'date-time',
            title: 'Last Updated',
            description: 'Timestamp when the data was last updated.'
        },
        data_staleness_seconds: {
            type: 'number',
            title: 'Data Staleness Seconds',
            description: 'Number of seconds since the data was last updated.',
            default: 0
        },
        coin_type: {
            type: 'string',
            title: 'Coin Type',
            description: 'Cryptocurrency symbol (e.g., BTC)'
        },
        realized_pnl: {
            type: 'number',
            title: 'Realized Pnl',
            description: 'Realized P&L for this coin'
        },
        unrealized_pnl: {
            type: 'number',
            title: 'Unrealized Pnl',
            description: 'Unrealized P&L for this coin'
        },
        total_pnl: {
            type: 'number',
            title: 'Total Pnl',
            description: 'Total P&L for this coin'
        }
    },
    type: 'object',
    required: ['coin_type', 'realized_pnl', 'unrealized_pnl', 'total_pnl'],
    title: 'PnLByCoinResponse',
    description: 'Response model for P&L grouped by coin'
} as const;

export const PnLSummaryResponseSchema = {
    properties: {
        is_loading: {
            type: 'boolean',
            title: 'Is Loading',
            description: 'Indicates if the data is currently being refreshed or computed.',
            default: false
        },
        last_updated: {
            type: 'string',
            format: 'date-time',
            title: 'Last Updated',
            description: 'Timestamp when the data was last updated.'
        },
        data_staleness_seconds: {
            type: 'number',
            title: 'Data Staleness Seconds',
            description: 'Number of seconds since the data was last updated.',
            default: 0
        },
        realized_pnl: {
            type: 'number',
            title: 'Realized Pnl',
            description: 'Total realized profit/loss from closed trades'
        },
        unrealized_pnl: {
            type: 'number',
            title: 'Unrealized Pnl',
            description: 'Total unrealized profit/loss from open positions'
        },
        total_pnl: {
            type: 'number',
            title: 'Total Pnl',
            description: 'Sum of realized and unrealized P&L'
        },
        total_trades: {
            type: 'integer',
            title: 'Total Trades',
            description: 'Total number of trades executed'
        },
        winning_trades: {
            type: 'integer',
            title: 'Winning Trades',
            description: 'Number of profitable trades'
        },
        losing_trades: {
            type: 'integer',
            title: 'Losing Trades',
            description: 'Number of unprofitable trades'
        },
        win_rate: {
            type: 'number',
            title: 'Win Rate',
            description: 'Percentage of winning trades (0-1.0)'
        },
        profit_factor: {
            type: 'number',
            title: 'Profit Factor',
            description: 'Ratio of gross profit to gross loss'
        },
        total_profit: {
            type: 'number',
            title: 'Total Profit',
            description: 'Total gross profit'
        },
        total_loss: {
            type: 'number',
            title: 'Total Loss',
            description: 'Total gross loss'
        },
        average_win: {
            type: 'number',
            title: 'Average Win',
            description: 'Average profit per winning trade'
        },
        average_loss: {
            type: 'number',
            title: 'Average Loss',
            description: 'Average loss per losing trade'
        },
        largest_win: {
            type: 'number',
            title: 'Largest Win',
            description: 'Largest single profit'
        },
        largest_loss: {
            type: 'number',
            title: 'Largest Loss',
            description: 'Largest single loss'
        },
        max_drawdown: {
            type: 'number',
            title: 'Max Drawdown',
            description: 'Maximum peak-to-trough decline'
        },
        sharpe_ratio: {
            type: 'number',
            title: 'Sharpe Ratio',
            description: 'Risk-adjusted return metric'
        },
        total_volume: {
            type: 'number',
            title: 'Total Volume',
            description: 'Total trading volume'
        },
        total_fees: {
            type: 'number',
            title: 'Total Fees',
            description: 'Total trading fees paid'
        }
    },
    type: 'object',
    required: ['realized_pnl', 'unrealized_pnl', 'total_pnl', 'total_trades', 'winning_trades', 'losing_trades', 'win_rate', 'profit_factor', 'total_profit', 'total_loss', 'average_win', 'average_loss', 'largest_win', 'largest_loss', 'max_drawdown', 'sharpe_ratio', 'total_volume', 'total_fees'],
    title: 'PnLSummaryResponse',
    description: 'Response model for P&L summary'
} as const;

export const PositionPublicSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id',
            description: 'The UUID of the user who owns this position.'
        },
        coin_type: {
            type: 'string',
            maxLength: 20,
            title: 'Coin Type',
            description: "The type of coin (e.g., 'BTC', 'ETH')."
        },
        quantity: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Quantity',
            description: 'The quantity of the coin held.'
        },
        average_price: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Average Price',
            description: 'The average price at which the position was acquired.'
        },
        total_cost: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Cost',
            description: 'The total cost basis of the position.'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id',
            description: 'The unique identifier for the position.'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At',
            description: 'The timestamp when the position was first created.'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At',
            description: 'The timestamp when the position was last updated.'
        },
        current_value: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Value',
            description: 'The current market value of the position.'
        },
        unrealized_pnl: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unrealized Pnl',
            description: 'The unrealized profit or loss.'
        }
    },
    type: 'object',
    required: ['user_id', 'coin_type', 'quantity', 'average_price', 'total_cost', 'id', 'created_at', 'updated_at'],
    title: 'PositionPublic',
    description: 'Schema for returning position via API'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RealizedPnLResponseSchema = {
    properties: {
        is_loading: {
            type: 'boolean',
            title: 'Is Loading',
            description: 'Indicates if the data is currently being refreshed or computed.',
            default: false
        },
        last_updated: {
            type: 'string',
            format: 'date-time',
            title: 'Last Updated',
            description: 'Timestamp when the data was last updated.'
        },
        data_staleness_seconds: {
            type: 'number',
            title: 'Data Staleness Seconds',
            description: 'Number of seconds since the data was last updated.',
            default: 0
        },
        realized_pnl: {
            type: 'number',
            title: 'Realized Pnl',
            description: 'Total realized profit/loss'
        }
    },
    type: 'object',
    required: ['realized_pnl'],
    title: 'RealizedPnLResponse',
    description: 'Response model for realized P&L'
} as const;

export const RiskRuleCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        rule_type: {
            type: 'string',
            title: 'Rule Type',
            description: 'max_daily_loss, max_position_size, etc.'
        },
        value: {
            additionalProperties: true,
            type: 'object',
            title: 'Value',
            default: {}
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['name', 'rule_type'],
    title: 'RiskRuleCreate'
} as const;

export const RiskRulePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        rule_type: {
            type: 'string',
            title: 'Rule Type',
            description: 'max_daily_loss, max_position_size, etc.'
        },
        value: {
            additionalProperties: true,
            type: 'object',
            title: 'Value',
            default: {}
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'rule_type', 'id', 'created_at', 'updated_at'],
    title: 'RiskRulePublic'
} as const;

export const RiskRuleUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        rule_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rule Type'
        },
        value: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Value'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'RiskRuleUpdate'
} as const;

export const RiskRulesSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RiskRulePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RiskRules'
} as const;

export const SafetyStatusResponseSchema = {
    properties: {
        is_loading: {
            type: 'boolean',
            title: 'Is Loading',
            description: 'Indicates if the data is currently being refreshed or computed.',
            default: false
        },
        last_updated: {
            type: 'string',
            format: 'date-time',
            title: 'Last Updated',
            description: 'Timestamp when the data was last updated.'
        },
        data_staleness_seconds: {
            type: 'number',
            title: 'Data Staleness Seconds',
            description: 'Number of seconds since the data was last updated.',
            default: 0
        },
        status: {
            type: 'string',
            title: 'Status',
            description: 'Safety system status: active, triggered, disabled'
        },
        triggered_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Triggered At',
            description: 'When the safety mechanism was triggered'
        },
        triggered_by: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Triggered By',
            description: 'User or system that triggered it'
        }
    },
    type: 'object',
    required: ['status'],
    title: 'SafetyStatusResponse'
} as const;

export const StrategyPromotionCreateSchema = {
    properties: {
        algorithm_id: {
            type: 'string',
            format: 'uuid',
            title: 'Algorithm Id'
        },
        promotion_notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Promotion Notes'
        },
        performance_snapshot_json: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Performance Snapshot Json'
        }
    },
    type: 'object',
    required: ['algorithm_id'],
    title: 'StrategyPromotionCreate',
    description: 'Schema for requesting a strategy promotion'
} as const;

export const StrategyPromotionPublicSchema = {
    properties: {
        algorithm_id: {
            type: 'string',
            format: 'uuid',
            title: 'Algorithm Id'
        },
        from_environment: {
            type: 'string',
            maxLength: 50,
            title: 'From Environment',
            default: 'lab'
        },
        to_environment: {
            type: 'string',
            maxLength: 50,
            title: 'To Environment',
            default: 'floor'
        },
        status: {
            type: 'string',
            maxLength: 20,
            title: 'Status',
            default: 'pending'
        },
        promotion_notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Promotion Notes'
        },
        performance_snapshot_json: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Performance Snapshot Json',
            description: 'JSON snapshot of backtest performance metrics at time of promotion'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_by: {
            type: 'string',
            format: 'uuid',
            title: 'Created By'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        reviewed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reviewed At'
        },
        reviewed_by: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reviewed By'
        },
        rejection_reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rejection Reason'
        }
    },
    type: 'object',
    required: ['algorithm_id', 'id', 'created_by', 'created_at', 'updated_at', 'reviewed_at', 'reviewed_by', 'rejection_reason'],
    title: 'StrategyPromotionPublic',
    description: 'Schema for returning strategy promotion via API'
} as const;

export const StrategyPromotionUpdateSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status',
            description: 'approved or rejected'
        },
        rejection_reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rejection Reason'
        }
    },
    type: 'object',
    required: ['status'],
    title: 'StrategyPromotionUpdate',
    description: 'Schema for reviewing a strategy promotion (approve/reject)'
} as const;

export const SystemSettingPublicSchema = {
    properties: {
        key: {
            type: 'string',
            maxLength: 100,
            title: 'Key'
        },
        value: {
            additionalProperties: true,
            type: 'object',
            title: 'Value',
            default: {}
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['key', 'updated_at'],
    title: 'SystemSettingPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TradeAuditCreateSchema = {
    properties: {
        agent_id: {
            type: 'string',
            maxLength: 100,
            title: 'Agent Id',
            description: 'ID of the agent making the decision'
        },
        decision: {
            type: 'string',
            maxLength: 20,
            title: 'Decision',
            description: 'BUY, SELL, or HOLD'
        },
        reason: {
            type: 'string',
            maxLength: 1000,
            title: 'Reason',
            description: 'Explanation for the decision'
        },
        confidence_score: {
            type: 'number',
            title: 'Confidence Score',
            description: 'Model confidence (0.0 - 1.0)',
            default: 0
        },
        asset: {
            type: 'string',
            maxLength: 20,
            title: 'Asset',
            description: 'The asset being traded (e.g. BTC)'
        },
        price_at_decision: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price At Decision'
        },
        is_executed: {
            type: 'boolean',
            title: 'Is Executed',
            description: 'Whether the trade was actually placed',
            default: false
        },
        execution_order_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Execution Order Id',
            description: 'Link to the Order if placed'
        },
        block_reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Block Reason',
            description: 'Reason if blocked by The Guard'
        }
    },
    type: 'object',
    required: ['agent_id', 'decision', 'reason', 'asset'],
    title: 'TradeAuditCreate'
} as const;

export const TradeAuditPublicSchema = {
    properties: {
        agent_id: {
            type: 'string',
            maxLength: 100,
            title: 'Agent Id',
            description: 'ID of the agent making the decision'
        },
        decision: {
            type: 'string',
            maxLength: 20,
            title: 'Decision',
            description: 'BUY, SELL, or HOLD'
        },
        reason: {
            type: 'string',
            maxLength: 1000,
            title: 'Reason',
            description: 'Explanation for the decision'
        },
        confidence_score: {
            type: 'number',
            title: 'Confidence Score',
            description: 'Model confidence (0.0 - 1.0)',
            default: 0
        },
        asset: {
            type: 'string',
            maxLength: 20,
            title: 'Asset',
            description: 'The asset being traded (e.g. BTC)'
        },
        price_at_decision: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price At Decision'
        },
        is_executed: {
            type: 'boolean',
            title: 'Is Executed',
            description: 'Whether the trade was actually placed',
            default: false
        },
        execution_order_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Execution Order Id',
            description: 'Link to the Order if placed'
        },
        block_reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Block Reason',
            description: 'Reason if blocked by The Guard'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Timestamp'
        }
    },
    type: 'object',
    required: ['agent_id', 'decision', 'reason', 'asset', 'id', 'timestamp'],
    title: 'TradeAuditPublic'
} as const;

export const TradeAuditsSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TradeAuditPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TradeAudits'
} as const;

export const UnrealizedPnLResponseSchema = {
    properties: {
        is_loading: {
            type: 'boolean',
            title: 'Is Loading',
            description: 'Indicates if the data is currently being refreshed or computed.',
            default: false
        },
        last_updated: {
            type: 'string',
            format: 'date-time',
            title: 'Last Updated',
            description: 'Timestamp when the data was last updated.'
        },
        data_staleness_seconds: {
            type: 'number',
            title: 'Data Staleness Seconds',
            description: 'Number of seconds since the data was last updated.',
            default: 0
        },
        unrealized_pnl: {
            type: 'number',
            title: 'Unrealized Pnl',
            description: 'Total unrealized profit/loss'
        }
    },
    type: 'object',
    required: ['unrealized_pnl'],
    title: 'UnrealizedPnLResponse',
    description: 'Response model for unrealized P&L'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        timezone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Timezone',
            default: 'UTC'
        },
        preferred_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preferred Currency',
            default: 'AUD'
        },
        risk_tolerance: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Risk Tolerance',
            default: 'medium'
        },
        trading_experience: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trading Experience',
            default: 'beginner'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserLLMCredentialsCreateSchema = {
    properties: {
        provider: {
            type: 'string',
            maxLength: 20,
            minLength: 1,
            title: 'Provider',
            description: 'LLM provider: openai, google, anthropic'
        },
        model_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Name',
            description: 'Model name (e.g., gpt-4, gemini-1.5-pro)'
        },
        api_key: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Api Key',
            description: 'API key from the provider'
        },
        is_default: {
            type: 'boolean',
            title: 'Is Default',
            description: 'Set as default LLM for this user',
            default: false
        }
    },
    type: 'object',
    required: ['provider', 'api_key'],
    title: 'UserLLMCredentialsCreate',
    description: 'Schema for creating user LLM credentials'
} as const;

export const UserLLMCredentialsPublicSchema = {
    properties: {
        provider: {
            type: 'string',
            maxLength: 20,
            title: 'Provider'
        },
        model_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Name'
        },
        is_default: {
            type: 'boolean',
            title: 'Is Default',
            default: false
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        api_key_masked: {
            type: 'string',
            title: 'Api Key Masked',
            description: 'Masked API key (last 4 characters visible)'
        },
        last_validated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Validated At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['provider', 'id', 'user_id', 'api_key_masked', 'last_validated_at', 'created_at', 'updated_at'],
    title: 'UserLLMCredentialsPublic',
    description: 'Schema for returning user LLM credentials via API (with masked API key)'
} as const;

export const UserLLMCredentialsValidateSchema = {
    properties: {
        provider: {
            type: 'string',
            title: 'Provider',
            description: 'LLM provider: openai, google, anthropic'
        },
        api_key: {
            type: 'string',
            title: 'Api Key',
            description: 'API key to validate'
        },
        model_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Name',
            description: 'Optional model name to test'
        }
    },
    type: 'object',
    required: ['provider', 'api_key'],
    title: 'UserLLMCredentialsValidate',
    description: 'Schema for validating an API key before saving'
} as const;

export const UserLLMCredentialsValidationResultSchema = {
    properties: {
        is_valid: {
            type: 'boolean',
            title: 'Is Valid'
        },
        provider: {
            type: 'string',
            title: 'Provider'
        },
        model_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Name'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        },
        details: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Details'
        }
    },
    type: 'object',
    required: ['is_valid', 'provider'],
    title: 'UserLLMCredentialsValidationResult',
    description: 'Response for API key validation'
} as const;

export const UserProfilePublicSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        timezone: {
            type: 'string',
            title: 'Timezone'
        },
        preferred_currency: {
            type: 'string',
            title: 'Preferred Currency'
        },
        risk_tolerance: {
            type: 'string',
            title: 'Risk Tolerance'
        },
        trading_experience: {
            type: 'string',
            title: 'Trading Experience'
        },
        has_coinspot_credentials: {
            type: 'boolean',
            title: 'Has Coinspot Credentials',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'timezone', 'preferred_currency', 'risk_tolerance', 'trading_experience'],
    title: 'UserProfilePublic',
    description: 'Public user profile response with OMC-specific fields'
} as const;

export const UserProfileUpdateSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        timezone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Timezone'
        },
        preferred_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preferred Currency'
        },
        risk_tolerance: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Risk Tolerance'
        },
        trading_experience: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trading Experience'
        }
    },
    type: 'object',
    title: 'UserProfileUpdate',
    description: 'User profile update request with validation'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        timezone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Timezone',
            default: 'UTC'
        },
        preferred_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preferred Currency',
            default: 'AUD'
        },
        risk_tolerance: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Risk Tolerance',
            default: 'medium'
        },
        trading_experience: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trading Experience',
            default: 'beginner'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        timezone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Timezone',
            default: 'UTC'
        },
        preferred_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preferred Currency',
            default: 'AUD'
        },
        risk_tolerance: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Risk Tolerance',
            default: 'medium'
        },
        trading_experience: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trading Experience',
            default: 'beginner'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        timezone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Timezone'
        },
        preferred_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preferred Currency'
        },
        risk_tolerance: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Risk Tolerance'
        },
        trading_experience: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trading Experience'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;