// This file is auto-generated by @hey-api/openapi-ts

export const AgentArtifactPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        artifact_type: {
            type: 'string',
            title: 'Artifact Type'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        file_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Path'
        },
        mime_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mime Type'
        },
        size_bytes: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size Bytes'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'session_id', 'artifact_type', 'name', 'description', 'file_path', 'mime_type', 'size_bytes', 'created_at'],
    title: 'AgentArtifactPublic',
    description: 'Schema for returning agent artifact via API'
} as const;

export const AgentSessionCreateSchema = {
    properties: {
        user_goal: {
            type: 'string',
            maxLength: 5000,
            minLength: 1,
            title: 'User Goal',
            description: 'Natural language trading goal'
        }
    },
    type: 'object',
    required: ['user_goal'],
    title: 'AgentSessionCreate',
    description: 'Schema for creating a new agent session'
} as const;

export const AgentSessionMessagePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        agent_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Agent Name'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'session_id', 'role', 'content', 'agent_name', 'created_at'],
    title: 'AgentSessionMessagePublic',
    description: 'Schema for returning agent session message via API'
} as const;

export const AgentSessionPublicSchema = {
    properties: {
        user_goal: {
            type: 'string',
            title: 'User Goal',
            description: 'Natural language trading goal from user'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        },
        result_summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Result Summary'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        }
    },
    type: 'object',
    required: ['user_goal', 'status', 'id', 'user_id', 'error_message', 'result_summary', 'created_at', 'updated_at', 'completed_at'],
    title: 'AgentSessionPublic',
    description: 'Schema for returning agent session via API'
} as const;

export const AgentSessionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AgentSessionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AgentSessionsPublic',
    description: 'Schema for returning multiple agent sessions'
} as const;

export const ApprovalDecisionSchema = {
    properties: {
        approved: {
            type: 'boolean',
            title: 'Approved'
        },
        reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        }
    },
    type: 'object',
    required: ['approved'],
    title: 'ApprovalDecision',
    description: 'User approval or rejection.'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ChoiceSelectionSchema = {
    properties: {
        selected_model: {
            type: 'string',
            title: 'Selected Model'
        }
    },
    type: 'object',
    required: ['selected_model'],
    title: 'ChoiceSelection',
    description: 'User selection from available choices.'
} as const;

export const ClarificationResponseSchema = {
    properties: {
        responses: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Responses'
        }
    },
    type: 'object',
    required: ['responses'],
    title: 'ClarificationResponse',
    description: 'User responses to clarification questions.'
} as const;

export const CoinspotCredentialsCreateSchema = {
    properties: {
        api_key: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Api Key'
        },
        api_secret: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Api Secret'
        }
    },
    type: 'object',
    required: ['api_key', 'api_secret'],
    title: 'CoinspotCredentialsCreate',
    description: 'Schema for creating Coinspot credentials'
} as const;

export const CoinspotCredentialsPublicSchema = {
    properties: {
        is_validated: {
            type: 'boolean',
            title: 'Is Validated'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        api_key_masked: {
            type: 'string',
            title: 'Api Key Masked',
            description: 'Masked API key (last 4 characters visible)'
        },
        last_validated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Validated At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['is_validated', 'id', 'user_id', 'api_key_masked', 'last_validated_at', 'created_at', 'updated_at'],
    title: 'CoinspotCredentialsPublic',
    description: 'Schema for returning Coinspot credentials via API (with masked values)'
} as const;

export const CoinspotCredentialsUpdateSchema = {
    properties: {
        api_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Key'
        },
        api_secret: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Secret'
        }
    },
    type: 'object',
    title: 'CoinspotCredentialsUpdate',
    description: 'Schema for updating Coinspot credentials'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HistoricalPnLEntrySchema = {
    properties: {
        timestamp: {
            type: 'string',
            title: 'Timestamp'
        },
        realized_pnl: {
            type: 'number',
            title: 'Realized Pnl'
        },
        interval: {
            type: 'string',
            title: 'Interval'
        }
    },
    type: 'object',
    required: ['timestamp', 'realized_pnl', 'interval'],
    title: 'HistoricalPnLEntry',
    description: 'Single entry in historical P&L data'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const OverrideRequestSchema = {
    properties: {
        override_type: {
            type: 'string',
            title: 'Override Type'
        },
        override_data: {
            additionalProperties: true,
            type: 'object',
            title: 'Override Data'
        }
    },
    type: 'object',
    required: ['override_type', 'override_data'],
    title: 'OverrideRequest',
    description: 'User override request.'
} as const;

export const PnLByAlgorithmResponseSchema = {
    properties: {
        algorithm_id: {
            type: 'string',
            title: 'Algorithm Id'
        },
        realized_pnl: {
            type: 'number',
            title: 'Realized Pnl'
        },
        unrealized_pnl: {
            type: 'number',
            title: 'Unrealized Pnl'
        },
        total_pnl: {
            type: 'number',
            title: 'Total Pnl'
        }
    },
    type: 'object',
    required: ['algorithm_id', 'realized_pnl', 'unrealized_pnl', 'total_pnl'],
    title: 'PnLByAlgorithmResponse',
    description: 'Response model for P&L grouped by algorithm'
} as const;

export const PnLByCoinResponseSchema = {
    properties: {
        coin_type: {
            type: 'string',
            title: 'Coin Type'
        },
        realized_pnl: {
            type: 'number',
            title: 'Realized Pnl'
        },
        unrealized_pnl: {
            type: 'number',
            title: 'Unrealized Pnl'
        },
        total_pnl: {
            type: 'number',
            title: 'Total Pnl'
        }
    },
    type: 'object',
    required: ['coin_type', 'realized_pnl', 'unrealized_pnl', 'total_pnl'],
    title: 'PnLByCoinResponse',
    description: 'Response model for P&L grouped by coin'
} as const;

export const PnLSummaryResponseSchema = {
    properties: {
        realized_pnl: {
            type: 'number',
            title: 'Realized Pnl'
        },
        unrealized_pnl: {
            type: 'number',
            title: 'Unrealized Pnl'
        },
        total_pnl: {
            type: 'number',
            title: 'Total Pnl'
        },
        total_trades: {
            type: 'integer',
            title: 'Total Trades'
        },
        winning_trades: {
            type: 'integer',
            title: 'Winning Trades'
        },
        losing_trades: {
            type: 'integer',
            title: 'Losing Trades'
        },
        win_rate: {
            type: 'number',
            title: 'Win Rate'
        },
        profit_factor: {
            type: 'number',
            title: 'Profit Factor'
        },
        total_profit: {
            type: 'number',
            title: 'Total Profit'
        },
        total_loss: {
            type: 'number',
            title: 'Total Loss'
        },
        average_win: {
            type: 'number',
            title: 'Average Win'
        },
        average_loss: {
            type: 'number',
            title: 'Average Loss'
        },
        largest_win: {
            type: 'number',
            title: 'Largest Win'
        },
        largest_loss: {
            type: 'number',
            title: 'Largest Loss'
        },
        max_drawdown: {
            type: 'number',
            title: 'Max Drawdown'
        },
        sharpe_ratio: {
            type: 'number',
            title: 'Sharpe Ratio'
        },
        total_volume: {
            type: 'number',
            title: 'Total Volume'
        },
        total_fees: {
            type: 'number',
            title: 'Total Fees'
        }
    },
    type: 'object',
    required: ['realized_pnl', 'unrealized_pnl', 'total_pnl', 'total_trades', 'winning_trades', 'losing_trades', 'win_rate', 'profit_factor', 'total_profit', 'total_loss', 'average_win', 'average_loss', 'largest_win', 'largest_loss', 'max_drawdown', 'sharpe_ratio', 'total_volume', 'total_fees'],
    title: 'PnLSummaryResponse',
    description: 'Response model for P&L summary'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RealizedPnLResponseSchema = {
    properties: {
        realized_pnl: {
            type: 'number',
            title: 'Realized Pnl'
        }
    },
    type: 'object',
    required: ['realized_pnl'],
    title: 'RealizedPnLResponse',
    description: 'Response model for realized P&L'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UnrealizedPnLResponseSchema = {
    properties: {
        unrealized_pnl: {
            type: 'number',
            title: 'Unrealized Pnl'
        }
    },
    type: 'object',
    required: ['unrealized_pnl'],
    title: 'UnrealizedPnLResponse',
    description: 'Response model for unrealized P&L'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        timezone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Timezone',
            default: 'UTC'
        },
        preferred_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preferred Currency',
            default: 'AUD'
        },
        risk_tolerance: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Risk Tolerance',
            default: 'medium'
        },
        trading_experience: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trading Experience',
            default: 'beginner'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserLLMCredentialsCreateSchema = {
    properties: {
        provider: {
            type: 'string',
            maxLength: 20,
            minLength: 1,
            title: 'Provider',
            description: 'LLM provider: openai, google, anthropic'
        },
        model_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Name',
            description: 'Model name (e.g., gpt-4, gemini-1.5-pro)'
        },
        api_key: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Api Key',
            description: 'API key from the provider'
        },
        is_default: {
            type: 'boolean',
            title: 'Is Default',
            description: 'Set as default LLM for this user',
            default: false
        }
    },
    type: 'object',
    required: ['provider', 'api_key'],
    title: 'UserLLMCredentialsCreate',
    description: 'Schema for creating user LLM credentials'
} as const;

export const UserLLMCredentialsPublicSchema = {
    properties: {
        provider: {
            type: 'string',
            maxLength: 20,
            title: 'Provider'
        },
        model_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Name'
        },
        is_default: {
            type: 'boolean',
            title: 'Is Default',
            default: false
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        api_key_masked: {
            type: 'string',
            title: 'Api Key Masked',
            description: 'Masked API key (last 4 characters visible)'
        },
        last_validated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Validated At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['provider', 'id', 'user_id', 'api_key_masked', 'last_validated_at', 'created_at', 'updated_at'],
    title: 'UserLLMCredentialsPublic',
    description: 'Schema for returning user LLM credentials via API (with masked API key)'
} as const;

export const UserLLMCredentialsValidateSchema = {
    properties: {
        provider: {
            type: 'string',
            title: 'Provider',
            description: 'LLM provider: openai, google, anthropic'
        },
        api_key: {
            type: 'string',
            title: 'Api Key',
            description: 'API key to validate'
        },
        model_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Name',
            description: 'Optional model name to test'
        }
    },
    type: 'object',
    required: ['provider', 'api_key'],
    title: 'UserLLMCredentialsValidate',
    description: 'Schema for validating an API key before saving'
} as const;

export const UserLLMCredentialsValidationResultSchema = {
    properties: {
        is_valid: {
            type: 'boolean',
            title: 'Is Valid'
        },
        provider: {
            type: 'string',
            title: 'Provider'
        },
        model_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Name'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        },
        details: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Details'
        }
    },
    type: 'object',
    required: ['is_valid', 'provider'],
    title: 'UserLLMCredentialsValidationResult',
    description: 'Response for API key validation'
} as const;

export const UserProfilePublicSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        timezone: {
            type: 'string',
            title: 'Timezone'
        },
        preferred_currency: {
            type: 'string',
            title: 'Preferred Currency'
        },
        risk_tolerance: {
            type: 'string',
            title: 'Risk Tolerance'
        },
        trading_experience: {
            type: 'string',
            title: 'Trading Experience'
        },
        has_coinspot_credentials: {
            type: 'boolean',
            title: 'Has Coinspot Credentials',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'timezone', 'preferred_currency', 'risk_tolerance', 'trading_experience'],
    title: 'UserProfilePublic',
    description: 'Public user profile response with OMC-specific fields'
} as const;

export const UserProfileUpdateSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        timezone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Timezone'
        },
        preferred_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preferred Currency'
        },
        risk_tolerance: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Risk Tolerance'
        },
        trading_experience: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trading Experience'
        }
    },
    type: 'object',
    title: 'UserProfileUpdate',
    description: 'User profile update request with validation'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        timezone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Timezone',
            default: 'UTC'
        },
        preferred_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preferred Currency',
            default: 'AUD'
        },
        risk_tolerance: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Risk Tolerance',
            default: 'medium'
        },
        trading_experience: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trading Experience',
            default: 'beginner'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        timezone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Timezone',
            default: 'UTC'
        },
        preferred_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preferred Currency',
            default: 'AUD'
        },
        risk_tolerance: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Risk Tolerance',
            default: 'medium'
        },
        trading_experience: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trading Experience',
            default: 'beginner'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        timezone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Timezone'
        },
        preferred_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preferred Currency'
        },
        risk_tolerance: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Risk Tolerance'
        },
        trading_experience: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trading Experience'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;