// This file is auto-generated by @hey-api/openapi-ts

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const LLMCredentialValidationResponseSchema = {
    properties: {
        valid: {
            type: 'boolean',
            title: 'Valid'
        },
        message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message'
        }
    },
    type: 'object',
    required: ['valid'],
    title: 'LLMCredentialValidationResponse'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const UserLLMCredentialCreateSchema = {
    properties: {
        provider_name: {
            type: 'string',
            title: 'Provider Name'
        },
        api_key_encrypted: {
            type: 'string',
            title: 'Api Key Encrypted'
        },
        model_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Name'
        },
        is_default: {
            type: 'boolean',
            title: 'Is Default',
            default: false
        }
    },
    type: 'object',
    required: ['provider_name', 'api_key_encrypted'],
    title: 'UserLLMCredentialCreate'
} as const;

export const UserLLMCredentialPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        provider_name: {
            type: 'string',
            title: 'Provider Name'
        },
        model_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Name'
        },
        is_default: {
            type: 'boolean',
            title: 'Is Default'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            Title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'provider_name', 'is_default', 'created_at'],
    title: 'UserLLMCredentialPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;