// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetLlmCredentialsApiV1UsersMeLlmCredentialsGetResponse, CreateLlmCredentialApiV1UsersMeLlmCredentialsPostData, CreateLlmCredentialApiV1UsersMeLlmCredentialsPostResponse, DeleteLlmCredentialApiV1UsersMeLlmCredentialsCredentialIdDeleteData, DeleteLlmCredentialApiV1UsersMeLlmCredentialsCredentialIdDeleteResponse, SetDefaultLlmCredentialApiV1UsersMeLlmCredentialsCredentialIdDefaultPutData, SetDefaultLlmCredentialApiV1UsersMeLlmCredentialsCredentialIdDefaultPutResponse, ValidateLlmCredentialsApiV1UsersMeLlmCredentialsValidatePostData, ValidateLlmCredentialsApiV1UsersMeLlmCredentialsValidatePostResponse } from './types.gen';

export class UsersService {
    /**
     * Get Llm Credentials
     * @returns UserLLMCredentialPublic Successful Response
     * @throws ApiError
     */
    public static getLlmCredentialsApiV1UsersMeLlmCredentialsGet(): CancelablePromise<GetLlmCredentialsApiV1UsersMeLlmCredentialsGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me/llm-credentials'
        });
    }
    
    /**
     * Create Llm Credential
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserLLMCredentialPublic Successful Response
     * @throws ApiError
     */
    public static createLlmCredentialApiV1UsersMeLlmCredentialsPost(data: CreateLlmCredentialApiV1UsersMeLlmCredentialsPostData): CancelablePromise<CreateLlmCredentialApiV1UsersMeLlmCredentialsPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/me/llm-credentials',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Llm Credential
     * @param data The data for the request.
     * @param data.credentialId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteLlmCredentialApiV1UsersMeLlmCredentialsCredentialIdDelete(data: DeleteLlmCredentialApiV1UsersMeLlmCredentialsCredentialIdDeleteData): CancelablePromise<DeleteLlmCredentialApiV1UsersMeLlmCredentialsCredentialIdDeleteResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me/llm-credentials/{credential_id}',
            path: {
                credential_id: data.credentialId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Set Default Llm Credential
     * @param data The data for the request.
     * @param data.credentialId
     * @returns UserLLMCredentialPublic Successful Response
     * @throws ApiError
     */
    public static setDefaultLlmCredentialApiV1UsersMeLlmCredentialsCredentialIdDefaultPut(data: SetDefaultLlmCredentialApiV1UsersMeLlmCredentialsCredentialIdDefaultPutData): CancelablePromise<SetDefaultLlmCredentialApiV1UsersMeLlmCredentialsCredentialIdDefaultPutResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/users/me/llm-credentials/{credential_id}/default',
            path: {
                credential_id: data.credentialId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Validate Llm Credentials
     * @param data The data for the request.
     * @param data.requestBody
     * @returns LLMCredentialValidationResponse Successful Response
     * @throws ApiError
     */
    public static validateLlmCredentialsApiV1UsersMeLlmCredentialsValidatePost(data: ValidateLlmCredentialsApiV1UsersMeLlmCredentialsValidatePostData): CancelablePromise<ValidateLlmCredentialsApiV1UsersMeLlmCredentialsValidatePostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/me/llm-credentials/validate',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}