// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LLMCredentialValidationResponse = {
    valid: boolean;
    message?: (string | null);
};

export type Message = {
    message: string;
};

export type UserLLMCredentialCreate = {
    provider_name: string;
    api_key_encrypted: string;
    model_name?: (string | null);
    is_default?: boolean;
};

export type UserLLMCredentialPublic = {
    id: string;
    provider_name: string;
    model_name?: (string | null);
    is_default: boolean;
    created_at: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type GetLlmCredentialsApiV1UsersMeLlmCredentialsGetResponse = (Array<UserLLMCredentialPublic>);

export type CreateLlmCredentialApiV1UsersMeLlmCredentialsPostData = {
    requestBody: UserLLMCredentialCreate;
};

export type CreateLlmCredentialApiV1UsersMeLlmCredentialsPostResponse = (UserLLMCredentialPublic);

export type DeleteLlmCredentialApiV1UsersMeLlmCredentialsCredentialIdDeleteData = {
    credentialId: string;
};

export type DeleteLlmCredentialApiV1UsersMeLlmCredentialsCredentialIdDeleteResponse = (Message);

export type SetDefaultLlmCredentialApiV1UsersMeLlmCredentialsCredentialIdDefaultPutData = {
    credentialId: string;
};

export type SetDefaultLlmCredentialApiV1UsersMeLlmCredentialsCredentialIdDefaultPutResponse = (UserLLMCredentialPublic);

export type ValidateLlmCredentialsApiV1UsersMeLlmCredentialsValidatePostData = {
    requestBody: UserLLMCredentialCreate;
};

export type ValidateLlmCredentialsApiV1UsersMeLlmCredentialsValidatePostResponse = (LLMCredentialValidationResponse);