// This file is auto-generated by @hey-api/openapi-ts

/**
 * Schema for returning agent artifact via API
 */
export type AgentArtifactPublic = {
    id: string;
    session_id: string;
    artifact_type: string;
    name: string;
    description: (string | null);
    file_path: (string | null);
    mime_type: (string | null);
    size_bytes: (number | null);
    created_at: string;
};

/**
 * Schema for creating a new agent session
 */
export type AgentSessionCreate = {
    /**
     * Natural language trading goal
     */
    user_goal: string;
};

/**
 * Schema for returning agent session message via API
 */
export type AgentSessionMessagePublic = {
    id: string;
    session_id: string;
    role: string;
    content: string;
    agent_name: (string | null);
    created_at: string;
};

/**
 * Schema for returning agent session via API
 */
export type AgentSessionPublic = {
    /**
     * Natural language trading goal from user
     */
    user_goal: string;
    status: string;
    id: string;
    user_id: string;
    error_message: (string | null);
    result_summary: (string | null);
    created_at: string;
    updated_at: string;
    completed_at: (string | null);
};

/**
 * Schema for returning multiple agent sessions
 */
export type AgentSessionsPublic = {
    data: Array<AgentSessionPublic>;
    count: number;
};

/**
 * User approval or rejection.
 */
export type ApprovalDecision = {
    approved: boolean;
    reason?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * User selection from available choices.
 */
export type ChoiceSelection = {
    selected_model: string;
};

/**
 * User responses to clarification questions.
 */
export type ClarificationResponse = {
    responses: {
        [key: string]: (string);
    };
};

/**
 * Schema for creating Coinspot credentials
 */
export type CoinspotCredentialsCreate = {
    api_key: string;
    api_secret: string;
};

/**
 * Schema for returning Coinspot credentials via API (with masked values)
 */
export type CoinspotCredentialsPublic = {
    is_validated: boolean;
    id: string;
    user_id: string;
    /**
     * Masked API key (last 4 characters visible)
     */
    api_key_masked: string;
    last_validated_at: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * Schema for updating Coinspot credentials
 */
export type CoinspotCredentialsUpdate = {
    api_key?: (string | null);
    api_secret?: (string | null);
};

/**
 * Single entry in historical P&L data
 */
export type HistoricalPnLEntry = {
    timestamp: string;
    realized_pnl: number;
    interval: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * User override request.
 */
export type OverrideRequest = {
    override_type: string;
    override_data: {
        [key: string]: unknown;
    };
};

/**
 * Response model for P&L grouped by algorithm
 */
export type PnLByAlgorithmResponse = {
    algorithm_id: string;
    realized_pnl: number;
    unrealized_pnl: number;
    total_pnl: number;
};

/**
 * Response model for P&L grouped by coin
 */
export type PnLByCoinResponse = {
    coin_type: string;
    realized_pnl: number;
    unrealized_pnl: number;
    total_pnl: number;
};

/**
 * Response model for P&L summary
 */
export type PnLSummaryResponse = {
    realized_pnl: number;
    unrealized_pnl: number;
    total_pnl: number;
    total_trades: number;
    winning_trades: number;
    losing_trades: number;
    win_rate: number;
    profit_factor: number;
    total_profit: number;
    total_loss: number;
    average_win: number;
    average_loss: number;
    largest_win: number;
    largest_loss: number;
    max_drawdown: number;
    sharpe_ratio: number;
    total_volume: number;
    total_fees: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Response model for realized P&L
 */
export type RealizedPnLResponse = {
    realized_pnl: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Response model for unrealized P&L
 */
export type UnrealizedPnLResponse = {
    unrealized_pnl: number;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    timezone?: (string | null);
    preferred_currency?: (string | null);
    risk_tolerance?: (string | null);
    trading_experience?: (string | null);
    password: string;
};

/**
 * Schema for creating user LLM credentials
 */
export type UserLLMCredentialsCreate = {
    /**
     * LLM provider: openai, google, anthropic
     */
    provider: string;
    /**
     * Model name (e.g., gpt-4, gemini-1.5-pro)
     */
    model_name?: (string | null);
    /**
     * API key from the provider
     */
    api_key: string;
    /**
     * Set as default LLM for this user
     */
    is_default?: boolean;
};

/**
 * Schema for returning user LLM credentials via API (with masked API key)
 */
export type UserLLMCredentialsPublic = {
    provider: string;
    model_name?: (string | null);
    is_default?: boolean;
    is_active?: boolean;
    id: string;
    user_id: string;
    /**
     * Masked API key (last 4 characters visible)
     */
    api_key_masked: string;
    last_validated_at: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * Schema for validating an API key before saving
 */
export type UserLLMCredentialsValidate = {
    /**
     * LLM provider: openai, google, anthropic
     */
    provider: string;
    /**
     * API key to validate
     */
    api_key: string;
    /**
     * Optional model name to test
     */
    model_name?: (string | null);
};

/**
 * Response for API key validation
 */
export type UserLLMCredentialsValidationResult = {
    is_valid: boolean;
    provider: string;
    model_name?: (string | null);
    error_message?: (string | null);
    details?: ({
    [key: string]: unknown;
} | null);
};

/**
 * Public user profile response with OMC-specific fields
 */
export type UserProfilePublic = {
    email: string;
    full_name?: (string | null);
    timezone: string;
    preferred_currency: string;
    risk_tolerance: string;
    trading_experience: string;
    has_coinspot_credentials?: boolean;
};

/**
 * User profile update request with validation
 */
export type UserProfileUpdate = {
    full_name?: (string | null);
    timezone?: (string | null);
    preferred_currency?: (string | null);
    risk_tolerance?: (string | null);
    trading_experience?: (string | null);
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    timezone?: (string | null);
    preferred_currency?: (string | null);
    risk_tolerance?: (string | null);
    trading_experience?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    timezone?: (string | null);
    preferred_currency?: (string | null);
    risk_tolerance?: (string | null);
    trading_experience?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    timezone?: (string | null);
    preferred_currency?: (string | null);
    risk_tolerance?: (string | null);
    trading_experience?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AgentCreateAgentSessionData = {
    requestBody: AgentSessionCreate;
};

export type AgentCreateAgentSessionResponse = (AgentSessionPublic);

export type AgentListAgentSessionsData = {
    limit?: number;
    skip?: number;
};

export type AgentListAgentSessionsResponse = (AgentSessionsPublic);

export type AgentGetAgentSessionData = {
    sessionId: string;
};

export type AgentGetAgentSessionResponse = (AgentSessionPublic);

export type AgentDeleteAgentSessionData = {
    sessionId: string;
};

export type AgentDeleteAgentSessionResponse = ({
    [key: string]: (string);
});

export type AgentGetSessionMessagesData = {
    sessionId: string;
};

export type AgentGetSessionMessagesResponse = (Array<AgentSessionMessagePublic>);

export type AgentGetSessionArtifactsData = {
    sessionId: string;
};

export type AgentGetSessionArtifactsResponse = (Array<AgentArtifactPublic>);

export type AgentCancelAgentSessionData = {
    sessionId: string;
};

export type AgentCancelAgentSessionResponse = ({
    [key: string]: (string);
});

export type AgentGetClarificationsData = {
    sessionId: string;
};

export type AgentGetClarificationsResponse = (unknown);

export type AgentProvideClarificationsData = {
    requestBody: ClarificationResponse;
    sessionId: string;
};

export type AgentProvideClarificationsResponse = (unknown);

export type AgentGetChoicesData = {
    sessionId: string;
};

export type AgentGetChoicesResponse = (unknown);

export type AgentSelectChoiceData = {
    requestBody: ChoiceSelection;
    sessionId: string;
};

export type AgentSelectChoiceResponse = (unknown);

export type AgentGetPendingApprovalsData = {
    sessionId: string;
};

export type AgentGetPendingApprovalsResponse = (unknown);

export type AgentApproveRequestData = {
    requestBody: ApprovalDecision;
    sessionId: string;
};

export type AgentApproveRequestResponse = (unknown);

export type AgentGetOverridePointsEndpointData = {
    sessionId: string;
};

export type AgentGetOverridePointsEndpointResponse = (unknown);

export type AgentApplyOverrideData = {
    requestBody: OverrideRequest;
    sessionId: string;
};

export type AgentApplyOverrideResponse = (unknown);

export type AgentDownloadArtifactData = {
    artifactId: string;
};

export type AgentDownloadArtifactResponse = (unknown);

export type AgentDeleteArtifactData = {
    artifactId: string;
};

export type AgentDeleteArtifactResponse = ({
    [key: string]: (string);
});

export type AgentGetArtifactStatsResponse = ({
    [key: string]: unknown;
});

export type CredentialsGetCredentialsResponse = (CoinspotCredentialsPublic);

export type CredentialsUpdateCredentialsData = {
    requestBody: CoinspotCredentialsUpdate;
};

export type CredentialsUpdateCredentialsResponse = (CoinspotCredentialsPublic);

export type CredentialsCreateCredentialsData = {
    requestBody: CoinspotCredentialsCreate;
};

export type CredentialsCreateCredentialsResponse = (CoinspotCredentialsPublic);

export type CredentialsDeleteCredentialsResponse = (Message);

export type CredentialsValidateCredentialsResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PnlGetPnlSummaryData = {
    /**
     * End date for P&L calculation (ISO format)
     */
    endDate?: (string | null);
    /**
     * Start date for P&L calculation (ISO format)
     */
    startDate?: (string | null);
};

export type PnlGetPnlSummaryResponse = (PnLSummaryResponse);

export type PnlGetPnlByAlgorithmData = {
    /**
     * End date for P&L calculation
     */
    endDate?: (string | null);
    /**
     * Start date for P&L calculation
     */
    startDate?: (string | null);
};

export type PnlGetPnlByAlgorithmResponse = (Array<PnLByAlgorithmResponse>);

export type PnlGetPnlByCoinData = {
    /**
     * End date for P&L calculation
     */
    endDate?: (string | null);
    /**
     * Start date for P&L calculation
     */
    startDate?: (string | null);
};

export type PnlGetPnlByCoinResponse = (Array<PnLByCoinResponse>);

export type PnlGetHistoricalPnlData = {
    /**
     * End date for historical data (required)
     */
    endDate: string;
    /**
     * Time interval (hour, day, week, month)
     */
    interval?: string;
    /**
     * Start date for historical data (required)
     */
    startDate: string;
};

export type PnlGetHistoricalPnlResponse = (Array<HistoricalPnLEntry>);

export type PnlGetRealizedPnlData = {
    /**
     * Filter by algorithm ID
     */
    algorithmId?: (string | null);
    /**
     * Filter by cryptocurrency (e.g., 'BTC')
     */
    coinType?: (string | null);
    /**
     * End date for P&L calculation
     */
    endDate?: (string | null);
    /**
     * Start date for P&L calculation
     */
    startDate?: (string | null);
};

export type PnlGetRealizedPnlResponse = (RealizedPnLResponse);

export type PnlGetUnrealizedPnlData = {
    /**
     * Filter by cryptocurrency (e.g., 'BTC')
     */
    coinType?: (string | null);
};

export type PnlGetUnrealizedPnlResponse = (UnrealizedPnLResponse);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserProfileResponse = (UserProfilePublic);

export type UsersUpdateUserProfileData = {
    requestBody: UserProfileUpdate;
};

export type UsersUpdateUserProfileResponse = (UserProfilePublic);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UsersListLlmCredentialsResponse = (Array<UserLLMCredentialsPublic>);

export type UsersCreateLlmCredentialsData = {
    requestBody: UserLLMCredentialsCreate;
};

export type UsersCreateLlmCredentialsResponse = (UserLLMCredentialsPublic);

export type UsersSetDefaultLlmCredentialData = {
    credentialId: string;
};

export type UsersSetDefaultLlmCredentialResponse = (UserLLMCredentialsPublic);

export type UsersDeleteLlmCredentialData = {
    credentialId: string;
};

export type UsersDeleteLlmCredentialResponse = (Message);

export type UsersValidateLlmCredentialData = {
    requestBody: UserLLMCredentialsValidate;
};

export type UsersValidateLlmCredentialResponse = (UserLLMCredentialsValidationResult);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);