# ServiceMonitor for Prometheus to scrape metrics from collectors and agents
# Part of the Prometheus Operator ecosystem

---
# ServiceMonitor for Backend API
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: omc-staging
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
# ServiceMonitor for Agents
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agents-monitor
  namespace: omc-staging
  labels:
    app: agents
spec:
  selector:
    matchLabels:
      app: agents
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
# PodMonitor for Collectors (since they're not behind a service)
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: collectors-monitor
  namespace: omc-staging
  labels:
    app: collectors
spec:
  selector:
    matchLabels:
      app: collectors
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 60s
      scrapeTimeout: 15s
