"""Add AuditLog model

Revision ID: 01dfca4f8758
Revises: 02ce9a858be9
Create Date: 2026-02-10 10:01:15.433604

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "01dfca4f8758"
down_revision = "02ce9a858be9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("audit_log",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
    sa.Column("action", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column("actor_id", sa.Uuid(), nullable=True),
    sa.Column("details", sa.JSON(), nullable=True),
    sa.Column("severity", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(["actor_id"], ["user.id"], ),
    sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audit_log")
    # ### end Alembic commands ###
