"""Add strategy promotion tables

Revision ID: 02ce9a858be9
Revises: l5m6n7o8p9q0
Create Date: 2026-01-25 00:10:20.073676

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '02ce9a858be9'
down_revision = 'l5m6n7o8p9q0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_promotions',
    sa.Column('algorithm_id', sa.Uuid(), nullable=False),
    sa.Column('from_environment', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('to_environment', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('promotion_notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('performance_snapshot_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithms.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_promotions_algorithm_id'), 'strategy_promotions', ['algorithm_id'], unique=False)
    op.create_index(op.f('ix_strategy_promotions_created_by'), 'strategy_promotions', ['created_by'], unique=False)
    op.create_index(op.f('ix_strategy_promotions_status'), 'strategy_promotions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_promotions_status'), table_name='strategy_promotions')
    op.drop_index(op.f('ix_strategy_promotions_created_by'), table_name='strategy_promotions')
    op.drop_index(op.f('ix_strategy_promotions_algorithm_id'), table_name='strategy_promotions')
    op.drop_table('strategy_promotions')
    # ### end Alembic commands ###
