"""Add TradeAudit model

Revision ID: 1d0434380682
Revises: 7fd841d4fbd0
Create Date: 2026-02-11 10:40:09.055281

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1d0434380682'
down_revision = '7fd841d4fbd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_audit',
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('asset', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('price_at_decision', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('is_executed', sa.Boolean(), nullable=False),
    sa.Column('execution_order_id', sa.Uuid(), nullable=True),
    sa.Column('block_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_audit_agent_id'), 'trade_audit', ['agent_id'], unique=False)
    op.create_index(op.f('ix_trade_audit_asset'), 'trade_audit', ['asset'], unique=False)
    op.create_index(op.f('ix_trade_audit_timestamp'), 'trade_audit', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_audit_timestamp'), table_name='trade_audit')
    op.drop_index(op.f('ix_trade_audit_asset'), table_name='trade_audit')
    op.drop_index(op.f('ix_trade_audit_agent_id'), table_name='trade_audit')
    op.drop_table('trade_audit')
    # ### end Alembic commands ###
