"""add total_votes to news_sentiment

Revision ID: 1dc7a9078780
Revises: d0ff5656d6f6
Create Date: 2026-03-04 08:53:13.915716

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1dc7a9078780'
down_revision = 'd0ff5656d6f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_sentiment', sa.Column('total_votes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_sentiment', 'total_votes')
    # ### end Alembic commands ###
