"""Add price_data_5min table

Revision ID: 2a5dad6f1c22
Revises: 483f8604ffbd
Create Date: 2025-11-15 03:06:17.571157

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2a5dad6f1c22'
down_revision = '58387c92ac18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_data_5min',
    sa.Column('coin_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('bid', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('ask', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('last', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_data_5min_coin_timestamp', 'price_data_5min', ['coin_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_price_data_5min_coin_type'), 'price_data_5min', ['coin_type'], unique=False)
    op.create_index(op.f('ix_price_data_5min_timestamp'), 'price_data_5min', ['timestamp'], unique=False)
    op.create_index('uq_price_data_5min_coin_timestamp', 'price_data_5min', ['coin_type', 'timestamp'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_price_data_5min_coin_timestamp', table_name='price_data_5min')
    op.drop_index(op.f('ix_price_data_5min_timestamp'), table_name='price_data_5min')
    op.drop_index(op.f('ix_price_data_5min_coin_type'), table_name='price_data_5min')
    op.drop_index('ix_price_data_5min_coin_timestamp', table_name='price_data_5min')
    op.drop_table('price_data_5min')
    # ### end Alembic commands ###
