"""Add collector table

Revision ID: 2c9581c54ad5
Revises: 1d0434380682
Create Date: 2026-02-19 14:44:02.380588

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2c9581c54ad5'
down_revision = '1d0434380682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_protocol_fundamentals_protocol_collected'), table_name='protocol_fundamentals')
    op.create_index('uq_protocol_fundamentals_protocol_date', 'protocol_fundamentals', ['protocol', sa.text("((collected_at AT TIME ZONE 'UTC')::date)")], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_protocol_fundamentals_protocol_date', table_name='protocol_fundamentals')
    op.create_index(op.f('ix_protocol_fundamentals_protocol_collected'), 'protocol_fundamentals', ['protocol', 'collected_at'], unique=False)
    # ### end Alembic commands ###
