"""actually_create_collector_tables

Revision ID: 52c98dcff535
Revises: 2c9581c54ad5
Create Date: 2026-02-19 15:25:47.907103

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '52c98dcff535'
down_revision = '2c9581c54ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('plugin_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_cron', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collector_name'), 'collector', ['name'], unique=True)
    op.create_table('news_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_item_link'), 'news_item', ['link'], unique=True)
    op.create_index(op.f('ix_news_item_source'), 'news_item', ['source'], unique=False)
    op.create_table('sentiment_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_score_asset'), 'sentiment_score', ['asset'], unique=False)
    op.create_index(op.f('ix_sentiment_score_source'), 'sentiment_score', ['source'], unique=False)
    op.create_index(op.f('ix_sentiment_score_timestamp'), 'sentiment_score', ['timestamp'], unique=False)
    op.create_table('signal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('asset', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_asset'), 'signal', ['asset'], unique=False)
    op.create_index(op.f('ix_signal_generated_at'), 'signal', ['generated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signal_generated_at'), table_name='signal')
    op.drop_index(op.f('ix_signal_asset'), table_name='signal')
    op.drop_table('signal')
    op.drop_index(op.f('ix_sentiment_score_timestamp'), table_name='sentiment_score')
    op.drop_index(op.f('ix_sentiment_score_source'), table_name='sentiment_score')
    op.drop_index(op.f('ix_sentiment_score_asset'), table_name='sentiment_score')
    op.drop_table('sentiment_score')
    op.drop_index(op.f('ix_news_item_source'), table_name='news_item')
    op.drop_index(op.f('ix_news_item_link'), table_name='news_item')
    op.drop_table('news_item')
    op.drop_index(op.f('ix_collector_name'), table_name='collector')
    op.drop_table('collector')
    # ### end Alembic commands ###
