"""add alert_rule and alert_log tables

Revision ID: 544f543b568c
Revises: 70c878b568ed
Create Date: 2026-03-01 10:39:17.183138

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '544f543b568c'
down_revision = '70c878b568ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rule',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('alert_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('min_severity', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=True),
    sa.Column('recipients', sa.JSON(), nullable=True),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_log',
    sa.Column('alert_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('channels_dispatched', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_log')
    op.drop_table('alert_rule')
    # ### end Alembic commands ###
