"""add enrichment_run table

Revision ID: 66cea171d358
Revises: 1dc7a9078780
Create Date: 2026-03-08 11:13:09.335034

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '66cea171d358'
down_revision = '1dc7a9078780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrichment_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enricher_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('items_enriched', sa.Integer(), nullable=False),
    sa.Column('items_skipped', sa.Integer(), nullable=False),
    sa.Column('items_failed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrichment_run_enricher_name'), 'enrichment_run', ['enricher_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrichment_run_enricher_name'), table_name='enrichment_run')
    op.drop_table('enrichment_run')
    # ### end Alembic commands ###
