"""add_exchangeohlcv_table_fixed

Revision ID: 70c878b568ed
Revises: 52c98dcff535
Create Date: 2026-02-22 02:16:57.172149

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '70c878b568ed'
down_revision = '52c98dcff535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_ohlcv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.DECIMAL(precision=20, scale=10), nullable=False),
    sa.Column('high', sa.DECIMAL(precision=20, scale=10), nullable=False),
    sa.Column('low', sa.DECIMAL(precision=20, scale=10), nullable=False),
    sa.Column('close', sa.DECIMAL(precision=20, scale=10), nullable=False),
    sa.Column('volume', sa.DECIMAL(precision=20, scale=10), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_ohlcv_exchange'), 'exchange_ohlcv', ['exchange'], unique=False)
    op.create_index('ix_exchange_ohlcv_exchange_symbol', 'exchange_ohlcv', ['exchange', 'symbol'], unique=False)
    op.create_index(op.f('ix_exchange_ohlcv_symbol'), 'exchange_ohlcv', ['symbol'], unique=False)
    op.create_index('ix_exchange_ohlcv_symbol_timestamp', 'exchange_ohlcv', ['symbol', 'timestamp'], unique=False)
    op.create_index(op.f('ix_exchange_ohlcv_timestamp'), 'exchange_ohlcv', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_ohlcv_timestamp'), table_name='exchange_ohlcv')
    op.drop_index('ix_exchange_ohlcv_symbol_timestamp', table_name='exchange_ohlcv')
    op.drop_index(op.f('ix_exchange_ohlcv_symbol'), table_name='exchange_ohlcv')
    op.drop_index('ix_exchange_ohlcv_exchange_symbol', table_name='exchange_ohlcv')
    op.drop_index(op.f('ix_exchange_ohlcv_exchange'), table_name='exchange_ohlcv')
    op.drop_table('exchange_ohlcv')
    # ### end Alembic commands ###
