"""Add Collector model and fix index

Revision ID: 7535b2a25e3c
Revises: 1d0434380682
Create Date: 2026-02-15 01:54:12.668331

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7535b2a25e3c'
down_revision = '1d0434380682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('schedule_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('schedule_interval', sa.Integer(), nullable=True),
    sa.Column('schedule_cron', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('ledger', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collector_name'), 'collector', ['name'], unique=True)
    op.drop_index(op.f('ix_protocol_fundamentals_protocol_collected'), table_name='protocol_fundamentals')
    op.create_index('uq_protocol_fundamentals_protocol_date', 'protocol_fundamentals', ['protocol', sa.literal_column("((collected_at AT TIME ZONE 'UTC')::date)")], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_protocol_fundamentals_protocol_date', table_name='protocol_fundamentals')
    op.create_index(op.f('ix_protocol_fundamentals_protocol_collected'), 'protocol_fundamentals', ['protocol', 'collected_at'], unique=False)
    op.drop_index(op.f('ix_collector_name'), table_name='collector')
    op.drop_table('collector')
    # ### end Alembic commands ###
