"""add_risk_management_models

Revision ID: 7fd841d4fbd0
Revises: 02ce9a858be9
Create Date: 2026-02-10 10:05:12.188421

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7fd841d4fbd0'
down_revision = '02ce9a858be9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_rule',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('rule_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_rule_name'), 'risk_rule', ['name'], unique=False)
    op.create_index(op.f('ix_risk_rule_rule_type'), 'risk_rule', ['rule_type'], unique=False)
    op.create_table('system_setting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_log',
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_event_type'), 'audit_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_agent_artifacts_artifact_type'), table_name='agent_artifacts')
    op.drop_index(op.f('ix_agent_artifacts_session_id'), table_name='agent_artifacts')
    op.drop_constraint(op.f('agent_artifacts_session_id_fkey'), 'agent_artifacts', type_='foreignkey')
    op.create_foreign_key(None, 'agent_artifacts', 'agent_sessions', ['session_id'], ['id'])
    op.drop_index(op.f('ix_agent_session_messages_created_at'), table_name='agent_session_messages')
    op.drop_index(op.f('ix_agent_session_messages_session_id'), table_name='agent_session_messages')
    op.drop_constraint(op.f('agent_session_messages_session_id_fkey'), 'agent_session_messages', type_='foreignkey')
    op.create_foreign_key(None, 'agent_session_messages', 'agent_sessions', ['session_id'], ['id'])
    op.drop_index(op.f('ix_agent_sessions_created_at'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_llm_credential_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_status'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_user_id'), table_name='agent_sessions')
    op.drop_constraint(op.f('agent_sessions_user_id_fkey'), 'agent_sessions', type_='foreignkey')
    op.drop_constraint(op.f('fk_agent_sessions_llm_credential_id'), 'agent_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'agent_sessions', 'user_llm_credentials', ['llm_credential_id'], ['id'])
    op.create_foreign_key(None, 'agent_sessions', 'user', ['user_id'], ['id'])
    op.create_index(op.f('ix_algorithms_created_by'), 'algorithms', ['created_by'], unique=False)
    op.create_index(op.f('ix_algorithms_status'), 'algorithms', ['status'], unique=False)
    op.alter_column('on_chain_metrics', 'metric_value',
               existing_type=sa.NUMERIC(precision=30, scale=8),
               nullable=True)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    # op.drop_index(op.f('ix_protocol_fundamentals_protocol_collected'), table_name='protocol_fundamentals')
    # op.create_index('uq_protocol_fundamentals_protocol_date', 'protocol_fundamentals', ['protocol', sa.literal_column('(collected_at::date)')], unique=True)
    op.drop_index(op.f('ix_user_llm_credentials_is_active'), table_name='user_llm_credentials')
    op.drop_index(op.f('ix_user_llm_credentials_is_default'), table_name='user_llm_credentials')
    op.drop_index(op.f('ix_user_llm_credentials_provider'), table_name='user_llm_credentials')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_llm_credentials_provider'), 'user_llm_credentials', ['provider'], unique=False)
    op.create_index(op.f('ix_user_llm_credentials_is_default'), 'user_llm_credentials', ['is_default'], unique=False)
    op.create_index(op.f('ix_user_llm_credentials_is_active'), 'user_llm_credentials', ['is_active'], unique=False)
    op.drop_index('uq_protocol_fundamentals_protocol_date', table_name='protocol_fundamentals')
    op.create_index(op.f('ix_protocol_fundamentals_protocol_collected'), 'protocol_fundamentals', ['protocol', 'collected_at'], unique=False)
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.alter_column('on_chain_metrics', 'metric_value',
               existing_type=sa.NUMERIC(precision=30, scale=8),
               nullable=False)
    op.drop_index(op.f('ix_algorithms_status'), table_name='algorithms')
    op.drop_index(op.f('ix_algorithms_created_by'), table_name='algorithms')
    op.drop_constraint(None, 'agent_sessions', type_='foreignkey')
    op.drop_constraint(None, 'agent_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_agent_sessions_llm_credential_id'), 'agent_sessions', 'user_llm_credentials', ['llm_credential_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('agent_sessions_user_id_fkey'), 'agent_sessions', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_agent_sessions_user_id'), 'agent_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_status'), 'agent_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_agent_sessions_llm_credential_id'), 'agent_sessions', ['llm_credential_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_created_at'), 'agent_sessions', ['created_at'], unique=False)
    op.drop_constraint(None, 'agent_session_messages', type_='foreignkey')
    op.create_foreign_key(op.f('agent_session_messages_session_id_fkey'), 'agent_session_messages', 'agent_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_agent_session_messages_session_id'), 'agent_session_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_session_messages_created_at'), 'agent_session_messages', ['created_at'], unique=False)
    op.drop_constraint(None, 'agent_artifacts', type_='foreignkey')
    op.create_foreign_key(op.f('agent_artifacts_session_id_fkey'), 'agent_artifacts', 'agent_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_agent_artifacts_session_id'), 'agent_artifacts', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_artifacts_artifact_type'), 'agent_artifacts', ['artifact_type'], unique=False)
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_event_type'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('system_setting')
    op.drop_index(op.f('ix_risk_rule_rule_type'), table_name='risk_rule')
    op.drop_index(op.f('ix_risk_rule_name'), table_name='risk_rule')
    op.drop_table('risk_rule')
    # ### end Alembic commands ###
