"""Add user profile fields

Revision ID: 8abf25dd5d93
Revises: a51f14ba7e3a
Create Date: 2025-11-15 22:55:34.099111

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8abf25dd5d93'
down_revision = 'a51f14ba7e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('user', sa.Column('preferred_currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.add_column('user', sa.Column('risk_tolerance', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('user', sa.Column('trading_experience', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'trading_experience')
    op.drop_column('user', 'risk_tolerance')
    op.drop_column('user', 'preferred_currency')
    op.drop_column('user', 'timezone')
    # ### end Alembic commands ###
