"""Add coinspot credentials table

Revision ID: a51f14ba7e3a
Revises: 74xslpy3kp6z
Create Date: 2025-11-15 22:42:18.306475

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a51f14ba7e3a'
down_revision = '74xslpy3kp6z'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_coinspot_credentials_user_id'), table_name='coinspot_credentials')
    op.alter_column('price_data_5min', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price_data_5min', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('idx_coinspot_credentials_user_id'), 'coinspot_credentials', ['user_id'], unique=False)
    # ### end Alembic commands ###
