"""add news_enrichment table with jsonb

Revision ID: b88cf0b670eb
Revises: 66cea171d358
Create Date: 2026-03-08 20:37:51.915995

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b88cf0b670eb'
down_revision = '66cea171d358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_enrichment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_item_link', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('enricher_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('enrichment_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('currencies', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['news_item_link'], ['news_item.link'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_item_link', 'enricher_name', 'enrichment_type', name='uq_enrichment')
    )
    op.create_index(op.f('ix_news_enrichment_enricher_name'), 'news_enrichment', ['enricher_name'], unique=False)
    op.create_index(op.f('ix_news_enrichment_news_item_link'), 'news_enrichment', ['news_item_link'], unique=False)

    # Add GIN indexes for JSONB and ARRAY columns
    op.execute('CREATE INDEX ix_enrichment_data ON news_enrichment USING GIN (data)')
    op.execute('CREATE INDEX ix_enrichment_currencies ON news_enrichment USING GIN (currencies)')
    op.execute('CREATE INDEX ix_enrichment_enricher_time ON news_enrichment (enricher_name, enriched_at DESC)')

    # Migrate data from news_keyword_match to news_enrichment
    op.execute("""
        INSERT INTO news_enrichment (news_item_link, enricher_name, enrichment_type, data, currencies, confidence, enriched_at)
        SELECT
            nkm.news_item_link,
            CASE WHEN nkm.source_collector = 'enrichment_llm' THEN 'llm_sentiment' ELSE 'keyword' END,
            CASE WHEN nkm.source_collector = 'enrichment_llm' THEN 'sentiment' ELSE 'keyword' END,
            jsonb_build_object(
                'keyword', nkm.keyword,
                'category', nkm.category,
                'direction', nkm.direction,
                'impact', nkm.impact,
                'match_context', nkm.match_context,
                'temporal_signal', nkm.temporal_signal
            ),
            nkm.currencies,
            1.0,
            nkm.matched_at
        FROM news_keyword_match nkm
        ON CONFLICT (news_item_link, enricher_name, enrichment_type) DO NOTHING
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_enrichment_enricher_time', table_name='news_enrichment')
    op.drop_index('ix_enrichment_currencies', table_name='news_enrichment')
    op.drop_index('ix_enrichment_data', table_name='news_enrichment')
    op.drop_index(op.f('ix_news_enrichment_news_item_link'), table_name='news_enrichment')
    op.drop_index(op.f('ix_news_enrichment_enricher_name'), table_name='news_enrichment')
    op.drop_table('news_enrichment')
    # ### end Alembic commands ###
