"""add news_keyword_match table

Revision ID: d0ff5656d6f6
Revises: 544f543b568c
Create Date: 2026-03-03 22:02:19.284376

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0ff5656d6f6'
down_revision = '544f543b568c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_keyword_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_item_link', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('impact', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('currencies', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('match_context', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('temporal_signal', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('source_collector', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['news_item_link'], ['news_item.link'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_item_link', 'keyword', 'source_collector', name='uq_keyword_match_link_kw_src')
    )
    op.create_index(op.f('ix_news_keyword_match_keyword'), 'news_keyword_match', ['keyword'], unique=False)
    op.create_index(op.f('ix_news_keyword_match_news_item_link'), 'news_keyword_match', ['news_item_link'], unique=False)
    op.create_index(op.f('ix_news_keyword_match_source_collector'), 'news_keyword_match', ['source_collector'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_keyword_match_source_collector'), table_name='news_keyword_match')
    op.drop_index(op.f('ix_news_keyword_match_news_item_link'), table_name='news_keyword_match')
    op.drop_index(op.f('ix_news_keyword_match_keyword'), table_name='news_keyword_match')
    op.drop_table('news_keyword_match')
    # ### end Alembic commands ###
