"""Add sequence_id_event_type_stage

Revision ID: d939ddf6ef1a
Revises: c2a4b6c8d0e2
Create Date: 2026-03-18 08:32:23.669193

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd939ddf6ef1a'
down_revision = 'c2a4b6c8d0e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_session_messages', sa.Column('sequence_id', sa.Integer(), nullable=True))
    op.add_column('agent_session_messages', sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('agent_session_messages', sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.drop_index(op.f('ix_enrichment_currencies'), table_name='news_enrichment', postgresql_using='gin')
    op.drop_index(op.f('ix_enrichment_data'), table_name='news_enrichment', postgresql_using='gin')
    op.drop_index(op.f('ix_enrichment_enricher_time'), table_name='news_enrichment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_enrichment_enricher_time'), 'news_enrichment', ['enricher_name', sa.literal_column('enriched_at DESC')], unique=False)
    op.create_index(op.f('ix_enrichment_data'), 'news_enrichment', ['data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_enrichment_currencies'), 'news_enrichment', ['currencies'], unique=False, postgresql_using='gin')
    op.drop_column('agent_session_messages', 'stage')
    op.drop_column('agent_session_messages', 'event_type')
    op.drop_column('agent_session_messages', 'sequence_id')
    # ### end Alembic commands ###
