"""Add ExchangeOHLCV table

Revision ID: ded56bc2360b
Revises: 52c98dcff535
Create Date: 2026-02-22 01:57:19.120231

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ded56bc2360b'
down_revision = '52c98dcff535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_protocol_fundamentals_protocol_date'), table_name='protocol_fundamentals')
    op.create_index('uq_protocol_fundamentals_protocol_date', 'protocol_fundamentals', ['protocol', sa.literal_column('(collected_at::date)')], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_protocol_fundamentals_protocol_date', table_name='protocol_fundamentals')
    op.create_index(op.f('uq_protocol_fundamentals_protocol_date'), 'protocol_fundamentals', ['protocol', sa.literal_column("((collected_at AT TIME ZONE 'UTC'::text)::date)")], unique=True)
    # ### end Alembic commands ###
